### ISSUE TITLE
[C4GT] User Interface for Doc Generator

### ISSUE THREAD

**Issue by ChakshuGautam** [Samagra-Development/PDF-Package#123]
## Project Details
Doc Generator is a tool to create PDFs from a variety of formats. It is used extensively in our programs where we need to share a PDF report of some data. Be it class reports, student reports or usage numbers of our solutions. 

[Templater](https://github.com/Samagra-Development/templater) a REST API service that can store, manage and render templates. A Template is like a well-defined format in which data can be entered. The output generated is according to the format defined in the template. Templater helps us simplify and enhance this process by providing multiple services such as Data transformation, Lambda API, Templater Playground, Support for multiple engines, etc.

Currently doc generator has its own backend. Moving to Templater as a backend will allow us to benefit from all the development happening at Templater in real time. It would also allow us to spend time on features other than input processing which would be powered by Templater.

## Features to be implemented 
User Interface for Doc Generator.

### What exists
The feature doesn't exist right now.

### What needs to be built
- [ ] #74 
- [ ] #76 

### Complexity  
High      

### Skills Required 
HTML, Python, Typescript, NestJS.

### Name of Mentors:        
@AnshulMalik 

### Project size
8 Weeks

## Milestones
- [ ] Understanding the requirements
- [ ] Understanding Doc Generator
- [ ] Understanding Templater
- [ ] Planning elements of doc generator that would move to templater
- [ ] Define approaches of the implementation
- [ ] Implement backend with templater
- [ ] Write tests to verify functionality

## C4GT
This issue is nominated for Code for GovTech (C4GT) 2023 edition. 
C4GT is India's first annual coding program to create a community that can build and contribute to global [Digital Public Goods](https://www.codeforgovtech.in/digitalpublicgoods). If you want to use Open Source GovTech to create impact, then this is the opportunity for you! More about C4GT here: https://codeforgovtech.in/

**Comment by Harshit-Raj-14** [comment]
Hello, @AnshulMalik !

I just went through the issue and am looking forward to submitting a proposal for the project. I deal regularly with front-end tasks, I am proficient with react and javascript, I have some UI/UX knowledge and I am eager to work on this project. I am really looking forward to working on this project and it would be great if you could give feedback on the proposal.

I would like to work on this project as soon as possible. Request you to assign me some good first issues. 

Thank You!!

**Comment by nitin1chandani** [comment]
Dear @AnshulMalik 
I have thoroughly reviewed the project details for "Doc Generator User Interface" and I am excited to work on this project as part of the C4GT program. I am planning to submit a proposal soon, outlining my approach and timeline for the implementation. I wanted to inform you that I have carefully gone through the issue and I feel confident about taking on this project and looking forward to working in this project.

Thankyou

**Comment by AnshulMalik** [comment]
Looking forward to your proposals @Harshit-Raj-14 @nitin1chandani

**Comment by nitin1chandani** [comment]
Yes sirr @AnshulMalik

**Comment by Bkmakwana2002** [comment]
Dear @AnshulMalik 
I am an undergraduate student from IIT Ropar, I have gone through the project thoroughly and have made a draft proposal for this project. Hoping to contribute to this project as it matches my skills.

Regards
Bhavya Kumar Makwana

**Comment by nitin1chandani** [comment]
Dear @AnshulMalik 
Sir I have mailed the proposal to you, can you please review it,
your feedback will be valuable to me.

Regards
Nitin Chandani

**Comment by Fayouzz** [comment]
Dear Mentor, I have submitted my proposal for "[C4GT] User Interface for Doc Generator #123". Looking forward to learning and conrtributing :)
Thank you!
